### ISSUE TITLE
Implement a new token type

### ISSUE THREAD

**Issue by anvari1313** [1995parham/pakhshi#2]
As the token type is returning the state of publishing or subscriptions, we need to define a new one that implements the ```Token```  interface and holds the state of each pub/sub on each broker.

Maybe we decide not to return the error if at least one pub/sub be done successfully. I think it can be configurable and the user should be able to set it.

**Comment by 1995parham** [comment]
I am trying to implement this interface for many tokens at the same time. the only remaining function is the `WaitTimeout` function which must wait with a timeout for all tokens.

**Comment by moeen** [comment]
I am trying to implement the `WaitTimeout` function.

**Comment by moeen** [comment]
I have implemented `WaitTimeout` function in #3.

**Comment by 1995parham** [comment]
I have merged it and I think the token type is ready. @anvari1313 can you please check and if you are okay too we can close this issue.

**Comment by anvari1313** [comment]
Yes, @1995parham I'm OK with it.
